#!/bin/bash

# Проверяем, запущен ли waybar
if pgrep -x "waybar" > /dev/null; then
    echo "Waybar запущен, убиваю процесс..."
    pkill -x waybar
    sleep 1  # Даём время для завершения процесса
fi

# Запускаем waybar заново
echo "Перезапускаю Waybar..."
waybar &

# Проверяем, успешно ли запустился waybar
sleep 1
if pgrep -x "waybar" > /dev/null; then
    echo "Waybar успешно перезапущен!"
else
    echo "Ошибка: Waybar не запустился."
fi
